### ISSUE TITLE
Form Load

### ISSUE THREAD

**Issue by OkancanCosar** [19Mehmet05/AesPasswordSystem#3]
Dummy bir proje olduğunu biliyorum ama test için bir form load'a 

>             AesPasswordAndSolition s = new AesPasswordAndSolition();
>             var sifreli = s.AesSifrele("okancan");
>             var temiz = s.AesSifre_Coz(sifreli);

gibi bişey eklenebilir.

**Comment by 19Mehmet05** [comment]
926d11c831c4a5e5c308b1019d1928c391ee6cfa ile projeye eklendi.
