### ISSUE TITLE
Class isimleri

### ISSUE THREAD

**Issue by OkancanCosar** [19Mehmet05/AesPasswordSystem#4]
İçerde senin kullandığın class isimlernde çeviri hataları var gibi gördüm. Onları kontrol edebilirsin.
`Base64Solition`, `Oparation` gibi

Ancak dışarıdan bu metodları kullanırken `AesPasswordAndSolition` yerine başka bişey mi bulsak? Yani Şifreleme algoritmamızı açığa vurmayan bişey ?

**Comment by OkancanCosar** [comment]
ArunaObfuscation olabilir.

string ArunaObfuscation.Obfuscate(string) // şifreleyen metod
string ArunaObfuscation.Enlighten(string) // şifreyi çözen

**Comment by 19Mehmet05** [comment]
10d599b56d603d1ced3c4f48140a3a34074f1f8a ile değişiklikler yapıldı
