### ISSUE TITLE
Gereksiz importlar

### ISSUE THREAD

**Issue by OkancanCosar** [19Mehmet05/AesPasswordSystem#5]
c# zaten bunları dikkate almıyor ama kod okunurluğu açısından kullanılmayan importları (`using`) kaldırmak iyi olabilir. Bazı yerlerde de `Base64Solition.cs` > `string anametin = ASCIIEncoding.ASCII.GetString(cozulenveri);` satırında IDE bu satırı sadeleştirebilirsin diye sana hatırlatma veriyor. Bunlarla kodlar daha okunaiblir oluyor.

eski
`string anametin = ASCIIEncoding.ASCII.GetString(cozulenveri);`
sadeleştirilmiş hali
`string anametin = Encoding.ASCII.GetString(cozulenveri);`

bu işlemler zorunlu değil tabi ama tekrar edeyim kod okunurluğu için gerekli olabiliyor.

**Comment by 19Mehmet05** [comment]
926d11c831c4a5e5c308b1019d1928c391ee6cfa ile sorun çözüldü.

**Comment by 19Mehmet05** [comment]
926d11c831c4a5e5c308b1019d1928c391ee6cfa ile sorun çözüldü
